name: Observability
options:
  bundleIdPrefix: com.ArtfulArchivesStudio
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "18.6"
    macOS: "15.6"
  developmentLanguage: en
  usesTabs: false
  indentWidth: 2

settings:
  DEVELOPMENT_TEAM: 49S7UFWWL9
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  CODE_SIGN_STYLE: Automatic
  SWIFT_VERSION: "5.0"
  STRING_CATALOG_GENERATE_SYMBOLS: YES
  SWIFT_EMIT_LOC_STRINGS: YES
  SWIFT_APPROACHABLE_CONCURRENCY: YES
  SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
  SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: YES
  ENABLE_PREVIEWS: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  LOCALIZATION_PREFERS_STRING_CATALOGS: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

targets:
  Observability:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Observability
        excludes:
          - "Info.plist"
    info:
      path: Observability/Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: Observability/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.ArtfulArchivesStudio.Observability
      PRODUCT_NAME: "$(TARGET_NAME)"
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
      TARGETED_DEVICE_FAMILY: "1,2,7"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"
      "LD_RUNPATH_SEARCH_PATHS[sdk=macosx*]": "@executable_path/../Frameworks"
      "INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=iphoneos*]": YES
      "INFOPLIST_KEY_UIApplicationSceneManifest_Generation[sdk=iphonesimulator*]": YES
      "INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=iphoneos*]": YES
      "INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents[sdk=iphonesimulator*]": YES
      "INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphoneos*]": YES
      "INFOPLIST_KEY_UILaunchScreen_Generation[sdk=iphonesimulator*]": YES
      "INFOPLIST_KEY_UIStatusBarStyle[sdk=iphoneos*]": UIStatusBarStyleDefault
      "INFOPLIST_KEY_UIStatusBarStyle[sdk=iphonesimulator*]": UIStatusBarStyleDefault
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
      ENABLE_APP_SANDBOX: YES
      ENABLE_HARDENED_RUNTIME: YES
      ENABLE_INCOMING_NETWORK_CONNECTIONS: YES
      ENABLE_OUTGOING_NETWORK_CONNECTIONS: YES
      AUTOMATION_APPLE_EVENTS: YES
      ENABLE_FILE_ACCESS_DOWNLOADS_FOLDER: readonly
      ENABLE_RESOURCE_ACCESS_AUDIO_INPUT: NO
      ENABLE_RESOURCE_ACCESS_BLUETOOTH: YES
      ENABLE_RESOURCE_ACCESS_CALENDARS: NO
      ENABLE_RESOURCE_ACCESS_CAMERA: NO
      ENABLE_RESOURCE_ACCESS_CONTACTS: NO
      ENABLE_RESOURCE_ACCESS_LOCATION: NO
      ENABLE_RESOURCE_ACCESS_PHOTO_LIBRARY: NO
      ENABLE_RESOURCE_ACCESS_PRINTING: NO
      ENABLE_RESOURCE_ACCESS_USB: NO
      ENABLE_USER_SELECTED_FILES: readwrite
      REGISTER_APP_GROUPS: YES
      RUNTIME_EXCEPTION_ALLOW_DYLD_ENVIRONMENT_VARIABLES: NO
      RUNTIME_EXCEPTION_ALLOW_JIT: YES
      RUNTIME_EXCEPTION_ALLOW_UNSIGNED_EXECUTABLE_MEMORY: NO
      RUNTIME_EXCEPTION_DEBUGGING_TOOL: NO
      RUNTIME_EXCEPTION_DISABLE_EXECUTABLE_PAGE_PROTECTION: NO
      RUNTIME_EXCEPTION_DISABLE_LIBRARY_VALIDATION: NO

  ObservabilityTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - path: ObservabilityTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.ArtfulArchivesStudio.ObservabilityTests
      PRODUCT_NAME: "$(TARGET_NAME)"
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
      TARGETED_DEVICE_FAMILY: "1,2,7"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Observability.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Observability"
      BUNDLE_LOADER: "$(TEST_HOST)"
      STRING_CATALOG_GENERATE_SYMBOLS: NO
      SWIFT_EMIT_LOC_STRINGS: NO
      IPHONEOS_DEPLOYMENT_TARGET: "26.1"
      MACOSX_DEPLOYMENT_TARGET: "26.0"

  ObservabilityUITests:
    type: bundle.ui-testing
    platform: [iOS, macOS]
    sources:
      - path: ObservabilityUITests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.ArtfulArchivesStudio.ObservabilityUITests
      PRODUCT_NAME: "$(TARGET_NAME)"
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
      TARGETED_DEVICE_FAMILY: "1,2,7"
      STRING_CATALOG_GENERATE_SYMBOLS: NO
      SWIFT_EMIT_LOC_STRINGS: NO
      IPHONEOS_DEPLOYMENT_TARGET: "26.1"
      MACOSX_DEPLOYMENT_TARGET: "26.0"
      TEST_TARGET_NAME: Observability

schemes:
  Observability:
    build:
      targets:
        Observability_iOS: all
        Observability_macOS: all
        ObservabilityTests_iOS: [test]
        ObservabilityTests_macOS: [test]
        ObservabilityUITests_iOS: [test]
        ObservabilityUITests_macOS: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ObservabilityTests_iOS
        - ObservabilityTests_macOS
        - ObservabilityUITests_iOS
        - ObservabilityUITests_macOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release